
import json, re, uuid
from datetime import datetime
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"

with open(DATA/"policies.json", encoding="utf-8") as f: POLICIES = json.load(f)
with open(DATA/"requests.json", encoding="utf-8") as f: REQUESTS = json.load(f)
with open(DATA/"tickets.json", encoding="utf-8") as f: TICKETS = json.load(f)

class InternalServiceAgent:
    """
    Policy-grounded agentic workflow:
    1. Understand intent
    2. Retrieve relevant policy + ticket precedent
    3. Apply decision/risk rules
    4. Resolve, ask a follow-up, or escalate
    5. Create a structured ticket when needed
    6. Append an audit event
    """
    def __init__(self):
        self.audit = []
        self.vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
        self.policy_matrix = self.vectorizer.fit_transform([p["title"]+" "+p["text"] for p in POLICIES])

    def retrieve(self, text, k=3):
        q = self.vectorizer.transform([text])
        scores = cosine_similarity(q, self.policy_matrix)[0]
        idx = scores.argsort()[::-1][:k]
        return [(POLICIES[i], float(scores[i])) for i in idx if scores[i] > 0]

    def ticket_precedent(self, text):
        words = set(re.findall(r"[a-z]{4,}", text.lower()))
        scored=[]
        for t in TICKETS:
            tw=set(re.findall(r"[a-z]{4,}", (t["issue"]+" "+t["status"]).lower()))
            overlap=len(words & tw)
            if overlap:
                scored.append((overlap,t))
        scored.sort(reverse=True, key=lambda x:x[0])
        return [x[1] for x in scored[:2]]

    def classify(self, text):
        s=text.lower()
        if any(x in s for x in ["phishing","malware","unauthorized access","suspicious email"]):
            return "security_incident"
        if "guest" in s and "wifi" in s or ("wi-fi" in s and "guest" in s):
            return "guest_wifi"
        if "password" in s and any(x in s for x in ["locked","lock","failed","attempt"]):
            return "password_lockout"
        if "vpn" in s:
            return "vpn"
        if "printer" in s or "paper jam" in s:
            return "printer"
        if "mailbox" in s or "mail" in s and "full" in s:
            return "mailbox"
        if "expense" in s:
            return "expense_access"
        if "home" in s and ("monitor" in s or "equipment" in s or "chair" in s):
            return "wfh_equipment"
        if "laptop" in s or "screen" in s or "computer" in s:
            return "laptop"
        if "install" in s or "extension" in s or "software" in s or "tool" in s:
            return "software"
        if "admin access" in s or ("access" in s and "server" in s):
            return "admin_access"
        return "unclear"

    def _ticket(self, user, issue, route, source_ids, priority="Normal"):
        tid = "AI-" + uuid.uuid4().hex[:8].upper()
        ticket = {
            "ticket_id": tid,
            "employee": user or "Unknown",
            "issue": issue,
            "route": route,
            "priority": priority,
            "source_ids": source_ids,
            "created_at": datetime.now().isoformat(timespec="seconds")
        }
        self.audit.append({"time":ticket["created_at"],"event":"TICKET_CREATED","details":ticket})
        return ticket

    def handle(self, text, employee=""):
        intent=self.classify(text)
        retrieved=self.retrieve(text)
        sources=[p["id"] for p,_ in retrieved]
        precedents=self.ticket_precedent(text)
        decision="resolve"
        route="IT"
        priority="Normal"
        follow_up=None
        response=""
        risk="Low"

        if intent=="security_incident":
            decision="escalate"; route="Security"; priority="Critical"; risk="High"
            response=("This is a security incident. Report it immediately to "
                      "security@veridian-corp.example. Do not forward the suspicious email "
                      "to other employees. I’m routing this to Security.")
        elif intent=="guest_wifi":
            response="Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket is required."
        elif intent=="password_lockout":
            response="You tried the password 6 times, so the 5-attempt lockout rule applies. IT must manually unlock the account; no approval is required."
            decision="escalate"; route="IT"; priority="High"
        elif intent=="vpn":
            if "contractor" in text.lower():
                response="Contractors need manager approval submitted via the access request form before VPN access is granted. I’m routing this as an access request."
                decision="escalate"; route="IT Access"; priority="Normal"
            elif "expired" in text.lower():
                response="VPN credentials expire every 90 days and must be renewed by the employee. A previous ticket (TK-1042) shows the same issue as a resolved case."
                decision="resolve"
            else:
                response="VPN access is automatic for full-time employees. Contractors require manager approval via the access request form. Credentials expire every 90 days and must be renewed by the employee."
        elif intent=="printer":
            response="First check the printer queue and restart the print spooler. If the issue persists, log a ticket with the printer’s asset tag."
            decision="resolve"
        elif intent=="mailbox":
            response="The default mailbox quota is 25GB. Archive old mail if you are nearing the limit. Any increase above 25GB needs manager approval and is capped at 50GB."
            decision="resolve"
        elif intent=="expense_access":
            response="Expense-tool access is granted by Finance, not IT. If your account already exists and you have a login/technical problem, IT can assist."
            decision="route"; route="Finance"; priority="Normal"
        elif intent=="wfh_equipment":
            response="Working remotely more than 3 days/week makes you eligible for a one-time home-office equipment allowance for a chair/monitor. Manager sign-off and Finance processing are required; IT handles shipping only after approval."
            decision="route"; route="Finance"; priority="Normal"
        elif intent=="software":
            response="Standard catalog software can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days."
            if "not in" in text.lower() or "extension" in text.lower() or "non-catalog" in text.lower():
                decision="escalate"; route="IT Security"; priority="Normal"
        elif intent=="laptop":
            low=text.lower()
            if "dead" in low or "won’t turn on" in low or "wont turn on" in low:
                response=("The laptop appears to have a hardware failure. The laptop policy permits earlier replacement for verified hardware failure, "
                          "while the Asset Management extract says the standard refresh cycle is 4 years and early replacement outside that cycle requires Finance sign-off in addition to IT approval. "
                          "A technician should verify the failure before replacement is processed.")
                decision="escalate"; route="IT Hardware"; priority="High"
            elif "2 years" in low or "1 year" in low:
                response=("Because the laptop is only 2 years old, replacement would be outside the standard 4-year refresh cycle. "
                          "The stated policy requires Finance sign-off plus IT approval for early replacement. Since you asked about a fix, I’m routing this for hardware troubleshooting first.")
                decision="escalate"; route="IT Hardware"; priority="Normal"
            else:
                response=("Laptops are eligible for replacement after 3 years or earlier with verified hardware failure. "
                          "The Asset Management extract states a standard 4-year refresh cycle; early replacement outside that cycle requires Finance sign-off plus IT approval.")
                decision="escalate"; route="IT Hardware"; priority="Normal"
        elif intent=="admin_access":
            response=("I can’t approve admin/server access from the supplied policies. The request needs human review because authority and business justification are not defined here. "
                      "A historical ticket (TK-1050) was rejected when no business justification was provided; that is precedent, not a new policy.")
            decision="escalate"; route="Human IT Administrator"; priority="High"; risk="Medium"
        else:
            response="I need one detail before I can route this safely: what system/device is not working, and what exact error are you seeing?"
            decision="follow_up"; follow_up="system/device + exact error"
            risk="Medium"

        ticket=None
        if decision in ("escalate","route"):
            ticket=self._ticket(employee, text, route, sources, priority)
        self.audit.append({
            "time":datetime.now().isoformat(timespec="seconds"),
            "event":"AGENT_DECISION",
            "details":{"intent":intent,"decision":decision,"route":route,"risk":risk,"sources":sources}
        })
        return {
            "intent":intent,"decision":decision,"route":route,"priority":priority,
            "risk":risk,"response":response,"follow_up":follow_up,
            "sources":[{"id":p["id"],"title":p["title"],"score":round(s,3),"text":p["text"]} for p,s in retrieved],
            "precedents":precedents,"ticket":ticket
        }

    def handle_request_id(self, req_id):
        r=next((x for x in REQUESTS if x["id"].lower()==req_id.lower()),None)
        if not r: return None
        return self.handle(r["request"], r["employee"])

    def search(self, q):
        return self.handle(q)
